// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootstrap_travel_agency_MVC.Databeezu;

#nullable disable

namespace bootstraptravelagencyMVC.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20230116163831_Destinazioni")]
    partial class Destinazioni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bootstrap_travel_agency_MVC.Models.Destinazione", b =>
                {
                    b.Property<int>("DestinazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinazioneId"));

                    b.Property<string>("CittaArrivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinazioneId");

                    b.ToTable("Destinazioni");
                });

            modelBuilder.Entity("bootstrap_travel_agency_MVC.Models.Viaggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorCard")
                        .HasColumnType("int");

                    b.Property<int?>("DestinazioneId")
                        .HasColumnType("int");

                    b.Property<int>("GiorniViaggio")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeViaggio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumDestinazioni")
                        .HasColumnType("int");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DestinazioneId");

                    b.ToTable("Viaggi");
                });

            modelBuilder.Entity("bootstrap_travel_agency_MVC.Models.Viaggio", b =>
                {
                    b.HasOne("bootstrap_travel_agency_MVC.Models.Destinazione", null)
                        .WithMany("ViaggiPerDestinazione")
                        .HasForeignKey("DestinazioneId");
                });

            modelBuilder.Entity("bootstrap_travel_agency_MVC.Models.Destinazione", b =>
                {
                    b.Navigation("ViaggiPerDestinazione");
                });
#pragma warning restore 612, 618
        }
    }
}
